name: Build and Deploy
on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Minikube
        run: |
          minikube start
          eval $(minikube docker-env)

      - name: Build & Push Frontend
        run: |
          docker build -t ahmiitahir77/my-frontend:latest ./frontend
          docker push ahmiitahir77/my-frontend:latest

      - name: Build & Push Backend
        run: |
          docker build -t ahmiitahir77/my-backend:latest ./backend
          docker push ahmiitahir77/my-backend:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f frontend-deployment.yaml
          kubectl apply -f frontend-service.yaml
          kubectl apply -f backend-deployment.yaml
          kubectl apply -f backend-service.yaml